export const DEPARTMENTS = {
  DESIGN: "DESIGN",
  CAPTION: "CAPTION",
  SCHEDULE: "SCHEDULE",
}

export const COLUMNS = {
  TODO: "TODO",
  IN_PROGRESS: "IN_PROGRESS",
  DONE: "DONE",
}


export const DEPARTMENTSENUM= {
  DESIGN: "DESIGN",
  CAPTION: "CAPTION",
  SCHEDULE: "SCHEDULE",
}



export const USERS = {
  ADMIN: "ADMIN",
  EMPLOYEE: "EMPLOYEE",
  MANAGER : "MANAGER"
}